Name: "container_grype_check"
Description: "Check if all container artifacts are free of vulnerabilities"
ImageURL: "ghcr.io/opengovern/og-task-grype:local-v0.0.3"
Command: "/og-task-grype"
WorkloadType: "job"
EnvVars: {}
Interval: 0
NatsConfig:
  Stream: og_task_grype
  Topic: og_task_grype
  Consumer: og_task_grype
  ResultTopic: og_task_grype_result
  ResultConsumer: og_task_grype_result
ScaleConfig:
  Stream: og_task_grype
  Consumer: og_task_grype
  LagThreshold: "1"
  MinReplica: 0
  MaxReplica: 5