apiVersion: apps/v1
kind: Deployment
metadata:
  name: og-describer-template
  labels:
    app: og-describer-template
spec:
  minReadySeconds: 10
  replicas: 0
  selector:
    matchLabels:
      app: og-describer-template
  template:
    metadata:
      labels:
        app: og-describer-template
    spec:
      containers:
        - name: og-describer-template
          command: ["/og-describer-template"]
          imagePullPolicy: Always