apiVersion: apps/v1
kind: Deployment
metadata:
  name: og-describer-template-manuals
  labels:
    app: og-describer-template-manuals
spec:
  minReadySeconds: 10
  replicas: 0
  selector:
    matchLabels:
      app: og-describer-template-manuals
  template:
    metadata:
      labels:
        app: og-describer-template-manuals
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: opencomply-node
                    operator: In
                    values:
                      - worker
      containers:
        - name: og-describer-template
          command: [ "/og-describer-template" ]
          imagePullPolicy: Always
          env:
            - name: MANUAL_TRIGGERS
              value: "true"