# .github/workflows/deploy-service.yml
name: Deploy Service

on:
  workflow_call:
    inputs:
      service_name:
        description: 'Name of the service to deploy'
        required: true
        type: string
      dockerfile:
        description: 'Path to the Dockerfile'
        required: true
        type: string
      build_args:
        description: 'Build arguments for Docker'
        required: false
        type: string
    secrets:
      GHCR_PAT:
        description: 'GitHub Container Registry Personal Access Token'
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: docker
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download Build Artifact
        uses: actions/download-artifact@v3
        with:
          name: build
          path: .

      - name: Unpack Build Artifact
        run: |
          tar -xvf build.tar.gz
          ls -la ./build

      - name: Verify Build Directory
        run: |
          if [ -d "./build" ]; then
            echo "Build directory exists."
          else
            echo "Build directory does not exist!"
            exit 1
          fi

      - name: Log in to Container Registry
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/${{ inputs.service_name }}:${{ needs.tag.outputs.latest_tag }}
          file: ${{ inputs.dockerfile }}
          build-args: |
            ${{ inputs.build_args }}
          context: .
